[env:esp_wroom_32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
extra_scripts = pre:compile_commands.py
board_build.partitions = min_spiffs.csv
upload_protocol = esptool
monitor_speed = 115200
